enum {
  HUCK_TOKEN = 1,
  ID_TOKEN,
  NUM_TOKEN,
  ASSIGN_TOKEN,
  PLUS_TOKEN,
  MINUS_TOKEN,
  MULT_TOKEN,
  DIV_TOKEN,
  COMMA_TOKEN,
  STR_TOKEN,
  SPRIME_TOKEN,
  S_TOKEN,
  E_TOKEN,
  L_TOKEN,
  B_TOKEN
} TokenType;

enum {
  PROGRAM_PROD = 0,
  STATEMENT_PAIR_PROD,
  STATEMENT_NULL_PROD,
  STATEMENT_ASGN_PROD,
  STATEMENT_HUCK_PROD,
  EXPRESSION_NUM_PROD,
  EXPRESSION_ID_PROD,
  EXPRESSION_STR_PROD,
  EXPRESSION_OPR_PROD,
  LIST_PAIR_PROD,
  LIST_END_PROD,
  OPERATION_PLUS_PROD,
  OPERATION_MINUS_PROD,
  OPERATION_MULT_PROD,
  OPERATION_DIV_PROD
} ProductionType;
